# Generated by Django 2.2.16 on 2022-11-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeemail',
            name='email',
            field=models.EmailField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='codeemail',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
