# Generated by Django 2.2.16 on 2022-11-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_codeemail'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
