# Generated by Django 2.2.16 on 2022-11-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('adm', 'admin'), ('mdr', 'moderator'), ('usr', 'user')], default='usr', max_length=3),
        ),
    ]
