# Generated by Django 2.2.16 on 2022-11-22 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221122_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeemail',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
