# Generated by Django 2.2.16 on 2022-11-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20221122_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeemail',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='codeemail',
            name='username',
            field=models.CharField(max_length=150),
        ),
    ]
