# Generated by Django 2.2.16 on 2022-11-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_password'),
        ('users', '0002_auto_20221123_1156'),
    ]

    operations = [
    ]
