# Generated by Django 2.2.16 on 2022-11-23 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_merge_20221123_1325'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
