# Generated by Django 2.2.16 on 2022-11-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_code', models.CharField(blank=True, max_length=6)),
                ('email', models.EmailField(max_length=150)),
                ('username', models.CharField(max_length=150)),
            ],
        ),
    ]
