# Generated by Django 2.2.16 on 2022-11-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeemail',
            old_name='code',
            new_name='confirmation_code',
        ),
    ]
